package com.liu.common;

import java.io.Serializable;
import java.util.Date;

/**
 * @author dushuangcheng
 * @create 2016-09-28 10:59
 */
public class GameSwitch implements Serializable {
    private static final long serialVersionUID = 4643095183588314221L;
    private Long id;//This field was generated by MyBatis Generator.

    private String switchType;//开关类别


    private String name;//开关名称

    private Integer status;//开关状态 0：关闭 1 开启


    private String modifyUser;//操作人


    private Integer yn;


    private Date modified;

    private Date created;

    private String memo;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSwitchType() {
        return switchType;
    }

    public void setSwitchType(String switchType) {
        this.switchType = switchType;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getModifyUser() {
        return modifyUser;
    }

    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    public Integer getYn() {
        return yn;
    }

    public void setYn(Integer yn) {
        this.yn = yn;
    }

    public Date getModified() {
        return modified;
    }

    public void setModified(Date modified) {
        this.modified = modified;
    }

    public Date getCreated() {
        return created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }
}
